# This is a basic fully hermetic run of Lighthouse, that saves results as run artifacts.
name: LHCI-upload-artifact
on: push
jobs:
  hermetic-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on urls
        uses: ./
        with:
          urls: |
            https://treo.sh/
            https://treo.sh/demo
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci'
