name: LHCI-assert-on-budget-slack-notification
on: push
jobs:
  # This pass/fails a build with a budgets.json.
  assert-on-budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on urls and validate with budgets.json
        uses: ./
        with:
          urls: 'https://alekseykulikov.com/'
          budgetPath: '.github/lighthouse/budget.json'
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          logLevel: 'error'
          notifications: 'slack'