# Interpolate URLs with env variables.
name: LHCI-urls-interpolation
on: push
jobs:
  multiple-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on multiple URLs and interpolate env variables.
        uses: ./
        with:
          urls: |
            https://$DOMAIN/
            https://$DOMAIN/demo
          env:
            DOMAIN: treo.sh
