# This is a basic Lighthouse run over multiple URLs that uses temporary-public-storage.
name: LHCI-temporary-storage
on: push
jobs:
  multiple-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on URLs and store results to temporary-public-storage.
        uses: ./
        with:
          urls: |
            https://treo.sh/
            https://treo.sh/signup
            https://treo.sh/demo
          temporaryPublicStorage: true
