# This will run Lighthouse on a URL, then upload the results to a filesystem.
name: LHCI-upload-to-filesystem
on: push
jobs:
  populate-ci-server-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on a URL and upload data to file system.
        uses: ./
        with:
          urls: |
            https://treo.sh/
          fileSystemStoragePath: './lhci'
